### ISSUE TITLE
Running shell with "-l" switch could make this plugin throw cmake capabilities error

### ISSUE THREAD

**Issue by ghost** [rwols/CMakeBuilder#12]
## issue
refers to : https://github.com/rwols/CMakeBuilder/blob/591d107adb5b31a87766c5e39d4bf88ad8f94482/plugin.py#L54

If "-l" is passed, this plugin might  catch the error of shell configuration file instead of the real command to be checked via shell.

## demo
~/.bash_profile
```bash
not-a-command 'arg1'
```

run the shell command with the "-l" option:

```bash
$ bash -l -c 'echo hello'
/Users/test/.bash_profile: line 1: not-a-command: command not found
hello
$ bash  -c 'echo hello'
hello
```
<img width="413" alt="Screen Shot 2019-11-03 at 12 27 39 AM" src="https://user-images.githubusercontent.com/51267921/68073968-c9ab9180-fdd0-11e9-9b16-285bd8292a94.png">

**Comment by rwols** [comment]
The file Default/exec.py applies the `-l` flag too. You can see that via the command `View Package File`, and then opening the file Default/exec.py. Here's the relevant snippet from that file:

```python
        elif shell_cmd and sys.platform == "darwin":
            # Use a login shell on OSX, otherwise the users expected env vars won't be setup
            self.proc = subprocess.Popen(
                ["/usr/bin/env", "bash", "-l", "-c", shell_cmd],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                stdin=subprocess.PIPE,
                startupinfo=startupinfo,
                env=proc_env,
                preexec_fn=preexec_fn,
                shell=False)
```

This is because if you start SublimeText from the Dock, the user's custom $PATH is not loaded without `-l`. Starting SublimeText from the terminal has the same behavior as on Linux.

**Comment by rwols** [comment]
I made the error message more informative, feel free to make another issue if there are more problems.

**Comment by ghost** [comment]
> I made the error message more informative, feel free to make another issue if there are more problems.

 That's great!
