### ISSUE TITLE
How do I configure parallel builds?

### ISSUE THREAD

**Issue by alt-vlad1q** [rwols/CMakeBuilder#14]
Hello, in old versions of the plugin, system_builds were generated with the -j {max_count_threads} flag, how to set the flag in the new version? Because now by default, the assembly goes in one thread. Which method is correct?
```javascript
"env" : {"CMAKE_BUILD_PARALLEL_LEVEL": "8"}
```
or to class CmakeBuildCommand add:
```python 
cmd = [get_cmake_binary(), "--build", ".", "--config", config]
if build_target:
    cmd.extend(["--target", build_target])
cmd.extend(["-j8"])
```

**Comment by rwols** [comment]
You can set the environment variable `MAKE_FLAGS` to `-j8` I believe:

```
"env" : {"MAKE_FLAGS": "-j8"}
```

**Comment by rwols** [comment]
I would use CMAKE_BUILD_PARALLEL_LEVEL because your other option breaks generators like MSVC or Ninja

**Comment by alt-vlad1q** [comment]
well thank you
