### ISSUE TITLE
CMakeBuilder does not detect installed cmake binary.

### ISSUE THREAD

**Issue by meghadri** [rwols/CMakeBuilder#18]
Clean install of SublimeText3 on MacOS Catalina (10.15.7 (19H15)). 
Opened Project folder. e.g. The issue replicates on this repo. https://github.com/LearningByExample/ModernCppCI.git
Tools -> CMakeBuilder menu has only two options 'Diagnose (...)' and 'New Project'
Diagnosis results in the following output. 
╒═══════════════╤═════════╤══════════════════╕
 │ CHECK                           │   VALUE          │ SUGGESTION/FIX                  │
╞═══════════════╪═════════╪══════════════════╡
 │ cmake present              │       0                │ Install cmake                         │
╘═══════════════╧═════════╧══════════════════╛

The PATH env variable to include the location of the cmake executable is set in ~/.bashrc

Probably something simple that I am missing?

Thanks.

**Comment by rwols** [comment]
Yes, you need to update your $PATH in

- `~/.profile` if you're using bash,
- `~/.zprofile` if you're using zsh,
- `~/.config/fish/config.fish` if you're using fish.

**Comment by meghadri** [comment]
The location of the cmake binary is on the path. Added it in ~/.profile (using bash). No change in output.

**Comment by rwols** [comment]
Did you source your profile again in bash and then restarted ST?

```bash
subl ~/.profile
source ~/.profile
subl .
```

(or restart Terminal/iTerm)

**Comment by rwols** [comment]
Also, please open the console in ST with View > Show Console, and run the following in that console:

```
import os; os.environ["PATH"]
```

**Comment by rwols** [comment]
I'll assume this is fixed. Ping me if you're still blocked on this.
