### ISSUE TITLE
More strict check on "build_folder" parameter

### ISSUE THREAD

**Issue by eugene-babichenko** [rwols/CMakeBuilder#2]
Can you check macros in "build_folder" before substitute them? I wasn't able to work on a project because of an untracked typo in ${project_path}. In fact, the macro with the typo was just skipped and CMakeBuilder tried to create /build folder in the root directory getting 'Permission denied' error.

**Comment by rwols** [comment]
I put the creation of the folder in a try/catch block. Sublime will print an error message when it can't create the build folder now. See 62773de63a17e132fc2edecb6848dcc7ce2a1cee.

**Comment by rwols** [comment]
I'm not sure if I can do anything about checking the macro's themselves. That should be sublime's job. It seems when it encounters an unknown macro it will just substitute the empty string.

**Comment by eugene-babichenko** [comment]
Thank you for the quick feedback! Seems like your fix helped.
I reviewed your code on variables expansion, instead of `sublime.expand_variables` you can use [native Python template strings](https://docs.python.org/3.6/library/string.html#template-strings) if the `strings` module is fully functional in Sublime Text. There is `Template.substitute` method which does exactly the same work, but throws an exception if it cannot find a value for a macro.

**Comment by rwols** [comment]
That's a good idea, I'll see what I can do.

**Comment by rwols** [comment]
The latest commit (e6cc48702bc3bf513473ca153927fbd2f0336f8c) should display an error message when during expansion an unknown variable is encountered.

I thought about adding more variables, like `machine` and `processor` for example, but then I realized that this will not play nicely with the `working_dir` of the `build_systems` array of the project file, so I let that idea go.

**Comment by eugene-babichenko** [comment]
The fix is working, thank you.
