### ISSUE TITLE
Question: How to run project artifacts under the build system??

### ISSUE THREAD

**Issue by pabloh84** [rwols/CMakeBuilder#26]
Maybe I am doing something wrong but I cannot figure out how to run the artifacts from within sublime. Could you please help?? 

Maybe adding a section about this in the README would help other users as well. 

### Steps to reproduce: 

1. Open Sublime
2. Invoke `CmakeBuilder: New Project...` and follow steps
3. Invoke `CmakeBuilder: Configure`
4. Invoke `Build with: Defaut` 
WORKS as expected. Executable "hello" is generated. 

<--- Everything is ok up to this point --->

5. Invoke either  `Build With: Default - Run: hello` or `Build With: Default - Run under GDB: hello`
A text box labeled "Command Line Arguments" appears and regardless of my input **nothing else happens**. 

### What I have tried: 

- Running the output program `hello` from cmd line works as expected
- I have tried to add a read input line at the end of the hello program to no avail. 
- `top` / `ps` do not show the program running in the background 
- Showing in menu `Tools` -> `Build Results` -> `Show Build Results` present this: 
```
[100%] Built target hello
[Finished in 61ms]
``` 
But no output from the program `"Hello, world!`

### Environment

- Ubuntu 23.04
- Sublime 4143
- CMakeBuilder v2.1.0 installed from Package Control
- cmake version 3.25.1
- GNU gdb (Ubuntu 13.1-2ubuntu2) 13.1
- g++ (Ubuntu 12.2.0-17ubuntu1) 12.2.0

**Comment by rwols** [comment]
Do you have the Terminus package installed?

**Comment by pabloh84** [comment]
Nop, didn't knew it was needed... 

After installation all works perfectly!! Thanks!!

**Comment by pabloh84** [comment]
Again, than you for the support and thank you for this great extension! Keep up the great work!
