### ISSUE TITLE
Implement server functionality

### ISSUE THREAD

**Issue by rwols** [rwols/CMakeBuilder#4]
https://cmake.org/cmake/help/v3.8/manual/cmake-server.7.html

- [x] Add basic functionality
- [x] Add configure
- [x] Add codemodel
- [x] Add include directories
- [x] Add build command (this'll replace the old way of writing all build targets to the project file)
- [x] Make sure things work in Windows
- [x] Make sure things work in Linux
- [x] Look into bug where the quick-select panel stays visible after selecting the first item
- [x] ~Maybe wait for cmake devs to fix output directory bug?~ [WONTDO]
- [x] Rewrite "active target" logic. It should not be in the project file because it changes often.
- [x] Make sure no exceptions are thrown in unexpected places.
- [x] Make sure the new changes are transparent for older users.
- [x] Use TerminalView integration for building & running a target.
- [ ] Make sure <kbd>super</kbd><kbd>shift</kbd><kbd>B</kbd> presents all possible targets.
- [x] Make the "active target" show up in the status bar when sublime restarts from a hot exit.

**Comment by KingKili** [comment]
With the release of Version 3.15 of CMake the Server functionality go deprecated. Shouldn't it be removed from the project or be replaced with the new cmake-file-api?
https://cmake.org/cmake/help/v3.15/manual/cmake-server.7.html

**Comment by rwols** [comment]
I totally forgot about this PR to be honest :) I've read about the file API and it seems to be the way forward. So yes, we should drop this PR entirely.

**Comment by rwols** [comment]
@KingKili see #10 

I have to say this file API is much more suited for cmake than the previous server API.

**Comment by KingKili** [comment]
@rwols 
I have tried it and it works great. But I think you can drop the minimum required version down to 3.14.
