### ISSUE TITLE
Visible escape codes in build output and not working regex for c++ project

### ISSUE THREAD

**Issue by fsenzel** [rwols/CMakeBuilder#6]
Hi,

I am trying to work with your plugin for generating a build system from CMake for a C++ project both at Linux and MacOS. While the configure and also the write out to the project file works, the subsequent build output fails: Although some part is colored, error messages have still ANSI escape codes visible (s. the attached pic). Furthermore, it is not possible to jump via F4 between error message. I also tried to replace the escape codes by using the plugin "SublimeANSI", however, without any success. Do you have any idea where I can tackle the problem?

![image](https://user-images.githubusercontent.com/14981507/29822023-4e860be4-8cca-11e7-86cf-71b82e383771.png)

**Comment by fsenzel** [comment]
I forgot to mention that I am using Sublime Text 3 together with the older plugin version CMakeBuild 1.0.1 since I am limited to CMake 3.5.1.

Thank you in advance!

**Comment by rwols** [comment]
Could you try using `"CMAKE_COLOR_MAKEFILE": false` in your `command_line_overrides`?

**Comment by rwols** [comment]
Also, could you tell me which compiler you are using?

**Comment by rwols** [comment]
Could you also try adding this in your `command_line_overrides`: `"CMAKE_CXX_FLAGS": "-fno-diagnostics-color"`

**Comment by fsenzel** [comment]
Thanks for your answer. Unfortunately, both additions in the "command_line_overrides" had no effect. Between the changes I also cleared the caches. At my Linux machine I am using gcc 5.4.0....

**Comment by rwols** [comment]
I'm trying to disable the colorized output.

In your terminal, what is the output of
```bash
echo $GCC_COLORS
```
(it could be nothing).

[See this page for more info about colorized diagnostics from GCC](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Message-Formatting-Options.html).

You could also try `"CMAKE_CXX_FLAGS": "-fdiagnostics-color=never"`.

Does the compiler give any warning about unused CXX flags? It should pick up `-fno-diagnostics-color`. When you look at the escape codes, you can see that it tries to print "bold red" with the code `[01;31m`.

Can you try compiling a file in your terminal with `-fno-diagnostics-color` and see if it prints colorized output?

**Comment by fsenzel** [comment]
It seems that I found the problem:

In our CMakeLists.txt we explicitly check for diagnostic colors:

"######### check for -fdiagnostics-color compiler option #########
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-fdiagnostics-color=always" HAS_DIAGNOSTICSCOLOR)
if(HAS_DIAGNOSTICSCOLOR)
  message(STATUS "Current compiler supports -fdiagnostics-color=always option.")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fdiagnostics-color=always")
elseif()
  message(STATUS "Current compiler does not support -fdiagnostics-color=always option.")
endif()"

If I comment that block, both the colors and the regex works out of the box without any command_line_overrides. Maybe the plugin does not work with the "-fdiagnostics-color=always" flag?

Btw, "echo $GCC_COLORS" returns indeed nothing. Furthermore, when compiling in the terminal with "-fno-diagnostics-color" compiles without any color output. However, this different behavior is also obvious since my CMakeList always switched the diagnostic colors on....

**Comment by rwols** [comment]
I'm glad you found the problem. Maybe remove that option in the CMakeLists file because the compiler should be smart enough to know by itself if colorized output should be used.

**Comment by fsenzel** [comment]
But many thanks for pointing me in the right direction. Everything now works great!
