### ISSUE TITLE
Cannot configure because of path interpretation on windows

### ISSUE THREAD

**Issue by theblackunknown** [rwols/CMakeBuilder#7]
Hello,

While trying CMakeBuilder v2, I encounter a problem during configuration.
It seems that my project path does not escape the '\' character and then it misinterpret the path

> The C compiler identification is MSVC 19.11.25507.1
> The CXX compiler identification is MSVC 19.11.25507.1
> Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
> CMake Error at D:/theblackunknown/Documents/GitHub/glog/build/CMakeFiles/CMakeTmp/CMakeLists.txt:11 (set):
>   Syntax error in cmake code at
> 
>     D:/theblackunknown/Documents/GitHub/glog/build/CMakeFiles/CMakeTmp/CMakeLists.txt:11
> 
>   when parsing string
> 
>     D:\theblackunknown\Documents\GitHub\glog/build/CMakeFiles/CMakeTmp
> 
>   Invalid character escape '\D'.
> 
> 
> CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
>   Failed to configure test project build system.
> Call Stack (most recent call first):
>   CMakeLists.txt:11 (project)
> 
> 
> Configuring incomplete, errors occurred!
> See also "D:/theblackunknown/Documents/GitHub/glog/build/CMakeFiles/CMakeOutput.log".

It is something that can be handled by the sublime plugin ?

**Comment by rwols** [comment]
Thanks for trying it out on Windows. I haven't tested that platform at all, so it's understandable things are going wrong there. It looks like it's getting confused at one of its own generated cmake files, so it may be a bug in the server itself. I'll keep you updated.

**Comment by rwols** [comment]
@theblackunknown Did you got this to work in some way? I have no idea what could cause this.

**Comment by theblackunknown** [comment]
Hey @rwols , I haven't tried to build glog recently.
I might give it a try this week, let's keep in touch

**Comment by rwols** [comment]
It doesn't depend on glog I think, just any basic project fails at configure-time. I've made an issue about it over at the cmake repo: https://gitlab.kitware.com/cmake/cmake/issues/17751

**Comment by theblackunknown** [comment]
What I mean is that I noticed this problem with `glog`, not that this is the problem but I would at least try to reproduce it

Otherwise, I have managed to successfully configure a simple project recently.
So I definitely need to try to reproduce it again on my side

**Comment by rwols** [comment]
[This commit](https://github.com/rwols/CMakeBuilder/commit/5b26fdd8e8a6d4153720d2bff692e722d9ba82a6) should fix the issue, tested on Win10.

**Comment by rwols** [comment]
Assuming this is fixed.
