### ISSUE TITLE
Latest version on PackageControl is obsolete

### ISSUE THREAD

**Issue by theblackunknown** [rwols/CMakeBuilder#8]
Hello CMakeBuilder enthusiasts !

I have noticed while using CMakeBuilder recently that the version installed with PackageControl is out-of-date, and leads to a situation where it is impossible to start CMake server

The error is shown as 

```
Exception in thread Thread-1181:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "exec in C:\Program Files\Sublime Text 3\Packages\Default.sublime-package", line 141, in read_fileno
AttributeError: 'Server' object has no attribute 'encoding'
```

But looking at the latest code on this repo - as of 19/02/2018 - the ``Server`` class has this attribute.
However the ``Server`` class from the package on PackageControl doesn't.

I am not aware on how to update package in PackageControl but is it something you can do please ?

[server.py-diff.txt](https://github.com/rwols/CMakeBuilder/files/1736409/server.py-diff.txt)

**Comment by rwols** [comment]
Hi @theblackunknown, the problem is that `encoding` was added to (I believe) the ProcessListener class of the Sublime Text API. Ideally, we should check with `sublime.version()` wether the version is high enough to use `encoding`, otherwise fall-back to the old behavior. I don't know exactly in which version `encoding` was added to `ProcessListener`. I'll have to figure this out some day soon.

**Comment by rwols** [comment]
Changes to ProcessListener were apparently made in version 3153. I figured I can just keep a `self.encoding = "utf-8"` line in there even for people on versions less than 3153. I just released a 2.0.0-beta prerelease with the fixes that were already present since 19/02/2018 in the repo.

**Comment by theblackunknown** [comment]
Yes, it seems that simply leaving the `encoding` attribute would do the job, good thing if you have pushed a release with the latest repo state !

I'll give it a try tomorrow

**Comment by rwols** [comment]
Assuming this is fixed.
