### ISSUE TITLE
Can't select "Visual Studio 14 2015 Win64"

### ISSUE THREAD

**Issue by a-ma72** [rwols/CMakeBuilder#9]
In my settings I select the compiler installed on my system:
"visual_studio_versions": [14]
But I can't select the Win64 version

This results in an error:
CMake Error: Error: generator : Visual Studio 14 2015
Does not match the generator used previously: Visual Studio 14 2015 Win64
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
[Finished in 0.2s with exit code 1]

**Comment by KingKili** [comment]
Looks to me like there was another generator in the build folder previously. Try deleting everything in the build folder and retry.

**Comment by a-ma72** [comment]
Yes, deleting the existing build folder (generated with the cmake gui) removes the generator match failure.
But I still can't select the 64-bit compiler. 32-bit is always the default...

**Comment by rwols** [comment]
I'll try to take a look this weekend.

**Comment by a-ma72** [comment]
Thank you!
Perhaps it would be possible to override the generator by project settings.

**Comment by rwols** [comment]
First of all, did you try setting `"target_architecture": "amd64"`?

**Comment by a-ma72** [comment]
Sometimes it's soo easy...
Yes, that solved my problem. All works fine now!
